=== Ramoona/banks-db/schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "properties": {
    "color": {
      "description": "Bank brand color",
      "required": true,
      "type": "string"
    },
    "country": {
      "description": "Two letters code of bank country (ISO 3166-1 alpha-2)",
      "required": true,
      "type": "string"
    },
    "engTitle": {
      "description": "Bank name in English",
      "required": true,
      "type": "string"
    },
    "localTitle": {
      "description": "Bank name in local language",
      "required": true,
      "type": "string"
    },
    "name": {
      "description": "Unique project code for the bank",
      "required": true,
      "type": "string"
    },
    "prefixes": {
      "items": {
        "minimum": 10000,
        "type": "number"
      },
      "minItems": 0,
      "required": true,
      "type": "array",
      "uniqueItems": true
    },
    "url": {
      "description": "Link to official bank website",
      "required": true,
      "type": "string"
    }
  },
  "title": "Bank schema",
  "type": "object"
}

=== Ramoona/banks-db/banks/belinvestbank.json
{
  "name": "belinvestbank",
  "prefixes": [
    401346,
    434484,
    434485,
    434486,
    434487,
    458291,
    547691,
    557749,
    557884,
    557885
  ],
  "country": "by",
  "localTitle": "Белинвестбанк",
  "engTitle": "Belinvestbank",
  "url": "http://www.belinvestbank.by/",
  "color": "#009881"
}

=== Ramoona/banks-db/banks/priorbank.json
{
  "name": "priorbank",
  "prefixes": [
    413059,
    416064,
    417770,
    437458,
    445987,
    458285,
    471326,
    472950,
    480949,
    491698,
    542645,
    548952,
    558349
  ],
  "country": "by",
  "localTitle": "Приорбанк",
  "engTitle": "Priorbank",
  "url": "http://www.priorbank.by",
  "color": "#FFFF00"
}

=== Ramoona/banks-db/banks/ru/sberbank.json
{
  "name": "sberbank",
  "prefixes": [
    427683,
    427685,
    639002,
    67758,
    427901,
    54693,
    54690,
    427644,
    427601,
    427631,
    42765,
    427466,
    427467,
    427468,
    427469,
    427470,
    427472,
    427475,
    427477,
    427638,
    427655,
    427688,
    546916

  ],
  "country": "ru",
  "localTitle": "Сбербанк",
  "engTitle": "Sberbank",
  "url": "https://www.sberbank.ru",
  "color": "#309c0b"
}
